name: Gendiff CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-verison: ['3.9', '3.10', '3.11']
        
    steps:
    - uses: actions/checkout@v4

    - uses: action/setup-python@v5
      with:
        python-verison: ${{ matrix.python-version }}

    - name: install uv
      run: |
        'pip install --upgrade pip'
        'pip install uv'

    - name: Install dependecies
      run: make install

    - name: Lint
      run: make lint

    - name: Test
      run: make test
